### PR TITLE
fix: rework accordion structure and add disabled state

### LINKED ISSUE #406: Verify and fix Accordion storybook
- Storybook is broken
image
image

### PR DESCRIPTION
**Pull request by krzysztofzuraw**
I want to merge this change because it adds a disabled state and after feedback from developers refactor the Accordion structure. You can see changes in table under:

| Before | After |
| ------- | ------- |
| `Accordion.Item.Trigger` | `Accordion.Trigger` |
| `Accordion.Item.Content` | `Accordion.Content` |

This PR closes #406

### Screenshots

CleanShot 2023-04-27 at 15 30 07@2x

### Pull Request Checklist

- [ ] New components are exported from `./src/components/index.ts`.
- [x] Storybook story is created and documentation properly generated.

### CODE REVIEW

File: src/components/Accordion/Item/Trigger.tsx [hunk 1]
```diff
@@ -9,24 +9,31 @@ import { Button } from "../../Button";
...
   ...rest
-}: AccordionProps) => (
+}: AccordionTriggerProps) => (
   <AccordionHeader asChild>
-    <AccordionTrigger asChild>
+    <AccordionTrigger
+      asChild
+      onClick={(e) => {
+        disabled && e.preventDefault();
+      }}
```
Comment (poulch) [inline src/components/Accordion/Item/Trigger.tsx:28]: question: Is not enough to add disabled to AccordionItem ?

**Review by poulch — APPROVED** [review]

File: src/components/Accordion/Item/Trigger.tsx (hunk 1 above)
Comment (krzysztofzuraw) [reply src/components/Accordion/Item/Trigger.tsx:28]: nope - I tried to do that but I think it did not work as we are using custom `Item` component with `asChild` prop so I had to hack it in this way

**Review by Droniu — APPROVED** [review]

File: src/components/Accordion/Accordion.stories.tsx [hunk 2]
```diff
@@ -1,5 +1,8 @@
+/* eslint-disable react/jsx-key */
 import { Meta, StoryObj } from "@storybook/react";
-import { Accordion } from "./index";
+import { Text } from "../..";
+
+import { Accordion } from ".";
```
Comment (andrzejewsky) [inline src/components/Accordion/Accordion.stories.tsx:5]: hmm but this is not how it's being consumed by the user. User will always use what's exported from the index and I think we should also render that here. It tests whether our imports works (including typings) and what exactly it renders

**Review by andrzejewsky — APPROVED** [review]
