### PR TITLE
fix: number input

### LINKED ISSUE #389: Create Number input
Create number input that accepts only numbers (especially important for Safari & Firefox)

### PR DESCRIPTION
**Pull request by krzysztofzuraw**
I want to merge this change because it allows to pass only numbers when `input` is type number. I also added support for `endAdorment` that can hold e.g currency.

This PR closes #389 

### Screenshots

CleanShot 2023-05-29 at 09 03 55@2x

### Pull Request Checklist

- [ ] New components are exported from `./src/components/index.ts`.
- [ ] Storybook story is created and documentation properly generated.

### CODE REVIEW

File: src/components/Input/helpers.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { KeyboardEvent } from "react";
+
+export const checkIfValidNumberInput = (event: KeyboardEvent<HTMLElement>) => {
+  // Check if input type number is valid as input type number doesn't currently work in browsers like Safari and Firefox
```
Comment (poulch) [inline src/components/Input/helpers.ts:4]: suggestion: I'd move this above checkIfValidNumberInput

**Review by poulch — DISMISSED** [review]

**Review by poulch — APPROVED** [review]
