### PR TITLE
fix: switch.item doesnt inherit box props

### LINKED ISSUE #511: Bug: Switch.Item doesnt inherit BoxProps
### What are you trying to achieve?

I want to set Switch.Item do display flex, so I can style icon alignment

### Steps to reproduce the problem

I can't set Box Props on this component

### What did you expect to happen?

It should inherit BoxProps so I can se `display="flex"` etc

### Additional information

_No response_

### Environment

Browser and version: …
OS and version: …

### PR DESCRIPTION
**Pull request by qunm00**
I want to merge this change because it allows Switch.Item to use Box Props

This PR closes #511 

### Pull Request Checklist

- [ ] New components are exported from `./src/components/index.ts`.
- [ ] The storybook story is created and documentation is properly generated.
- [ ] New component is wrapped in `forwardRef`.

### CODE REVIEW

**Review by andrzejewsky — DISMISSED** [review]

**Review by poulch — APPROVED** [review]

File: src/components/Switch/Item.tsx [hunk 1]
```diff
@@ -2,31 +2,35 @@ import * as Switch from "@radix-ui/react-radio-group";
...
-    disabled={disabled}
-    className={switchChild()}
-    {...rest}
-  >
-    {children}
-  </Switch.Item>
-);
+}: SwitchItemProps) => {
+  return (
+    <Switch.Item
```
Comment (krzysztofzuraw) [inline src/components/Switch/Item.tsx:24]: **Suggestion:** add `asChild` prop to `Switch.Item`

Thanks to that we will have one component in HTML instead of two.

Reference: https://www.radix-ui.com/primitives/docs/components/radio-group#item

**Review by krzysztofzuraw — APPROVED** [review]

**Review by poulch — APPROVED** [review]
